#
# Copyright (c) 2010-2017 Fabric Software Inc. All rights reserved.
#

Import('docEnv')
subDirs = ['Canvas', 'CAPI', 'DFG', 'Manipulation', 'SceneGraph', 'SceneHub', 'RTR', 'Splice', 'PolygonMeshStructure', 'GettingStarted']
inputImages = docEnv.Glob('*.png') + docEnv.Flatten(SConscript(dirs = subDirs))
Return('inputImages')
