mv ./Arnold/index.template.rst ./Arnold/index.rst
mv ./InlineDrawingGuide/index.template.rst ./InlineDrawingGuide/index.rst
mv ./InlineDrawingGuide/integration.template.rst ./InlineDrawingGuide/integration.rst
mv ./InlineDrawingGuide/intro.template.rst ./InlineDrawingGuide/intro.rst
mv ./InlineDrawingGuide/transition.template.rst ./InlineDrawingGuide/transition.rst
mv ./InlineDrawingGuide/usage.template.rst ./InlineDrawingGuide/usage.rst
mv ./KLTips/index.template.rst ./KLTips/index.rst
mv ./Maya/index.template.rst ./Maya/index.rst
mv ./Maya/install.template.rst ./Maya/install.rst
mv ./Maya/intro.template.rst ./Maya/intro.rst
mv ./Maya/usage.template.rst ./Maya/usage.rst
mv ./Nuke/index.template.rst ./Nuke/index.rst
mv ./OFX/index.template.rst ./OFX/index.rst
mv ./Scripting/index.template.rst ./Scripting/index.rst
mv ./Softimage/index.template.rst ./Softimage/index.rst
mv ./Softimage/install.template.rst ./Softimage/install.rst
mv ./Softimage/intro.template.rst ./Softimage/intro.rst
mv ./Softimage/usage.template.rst ./Softimage/usage.rst
mv ./SpliceAPI/integrations.template.rst ./SpliceAPI/integrations.rst
mv ./Workshops/edkworkshop.template.rst ./Workshops/edkworkshop.rst
mv ./Workshops/index.template.rst ./Workshops/index.rst
mv ./Workshops/klworkshop.template.rst ./Workshops/klworkshop.rst
mv ./Workshops/spliceapiworkshop.template.rst ./Workshops/spliceapiworkshop.rst
mv ./Workshops/splicedeformersworkshop.template.rst ./Workshops/splicedeformersworkshop.rst
mv ./Workshops/splicegeometryworkshop.template.rst ./Workshops/splicegeometryworkshop.rst
mv ./Workshops/splicemotionworkshop.template.rst ./Workshops/splicemotionworkshop.rst
